name: BetHelper-Heroku-Pinger
# This workflow is triggered at a scheduled interval of every 25 minutes
on:
  schedule:
    # * is a special character in YAML so you have to quote this string.
    # /15 denotes that it will run once every 15 minutes
    - cron:  '*/15 * * * *'

jobs:
  pinger_job:
    name: Ping heroku
    runs-on: ubuntu-latest
    env:
      URL: ${{ secrets.URL }}
    steps:
      - id: ping
        uses: larkonesvk/bethelper-pinger@main
